services:
  airport:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8001:8000"
    command: >
      sh -c "
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db


  db:
    image: postgres:alpine3.19
    restart: always
    env_file:
      - .env
