services:
  airport:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8001:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND = redis://redis:6379
    volumes:
      - my_media:/files/media
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis


  db:
    image: postgres:alpine3.19
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - my_db:$PGDATA

  redis:
    image: "redis:alpine"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A airport_service worker -l info -P eventlet
    depends_on:
      - db
      - redis
      - airport
    restart: on-failure
    env_file:
      - .env



  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A airport_service beat -l info
    depends_on:
      - db
      - redis
      - airport
    restart: on-failure
    env_file:
      - .env


volumes:
  my_db:
  my_media:
