# Generated by Django 5.0.6 on 2024-05-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport_api", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airplane",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="airplanetype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="airport",
            options={"ordering": ["name"]},
        ),
    ]
