# Generated by Django 5.0.6 on 2024-05-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport_api", "0007_airplane_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="flying_hours",
            field=models.FloatField(default=0),
        ),
    ]
